//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UroborosApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Log
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> log_datetime { get; set; }
        public string action { get; set; }
    
        public virtual users users { get; set; }
    }
}
