//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UroborosApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Learning_Goals
    {
        public int id { get; set; }
        public int User_id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Target_Date { get; set; }
        public bool Is_completed { get; set; }
        public System.DateTime Created_Date { get; set; }
    
        public virtual users users { get; set; }
    }
}
