//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UroborosApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Learning_Statistics
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> total_materials_learned { get; set; }
        public Nullable<double> avg_recall_score { get; set; }
    
        public virtual users users { get; set; }
    }
}
