//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UroborosApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repetition
    {
        public int id { get; set; }
        public Nullable<int> material_id { get; set; }
        public System.DateTime repetition_date { get; set; }
        public Nullable<int> recall_score { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
